### ISSUE TITLE
关于模型训练和性能

### ISSUE THREAD

**Issue by sid-022** [ZachL1/IAAD#1]
hello，请问这个关于TANet模型的训练怎么执行呢？ 关于训练后的模型大小是多少呢

**Comment by ZachL1** [comment]
你好，关于TANet的细节请参考 https://github.com/woshidandan/TANet-image-aesthetics-and-quality-assessment

**Comment by sid-022** [comment]
> 你好，关于TANet的细节请参考 https://github.com/woshidandan/TANet-image-aesthetics-and-quality-assessment

谢谢，还想问一下使用你的代码 应该怎么训练呢？
我运行了code里面的train.py 输出了以下信息 但并没有看的显卡在运行
![image](https://github.com/user-attachments/assets/a4caaac2-87da-4ff8-aac3-b41480f77948)
