### ISSUE TITLE
Three questions about model training

### ISSUE THREAD

**Issue by sid-022** [ZachL1/IAAD#2]
作者你好，我这边有三个问题，可以解答一下吗？ 谢谢😁
1. 关于这个模型训练代码该怎么运行呢？

2. 如果想用TAD66k数据集训练 应该修改哪里呢？
![image](https://github.com/user-attachments/assets/26250f0a-d958-4807-be1d-c22088c78a01)

3. 模型保存是仅保存权重参数吗

**Comment by ZachL1** [comment]
你好，我不是TANet或TAD66k的作者，这个代码库是我一年多前写的，当时尝试复现TANet作为基线，只记得复现的结果不太好，具体原因和细节已经不记得得了。关于TANet和TAD66k的相关问题请参考原作者仓库：https://github.com/woshidandan/TANet-image-aesthetics-and-quality-assessment
